load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

COMMIT = "1df596c0b7e2ed57b2e1025ddf7d40d9235d7b6d"
http_archive(
    name = "io_bazel_rules_go",
    sha256 = "141404b87e981d460277736094e2f56ca97104b1392c5ac1a90c171d450fd5a0",
    strip_prefix = "rules_go-" + COMMIT,
    urls = [
        "https://github.com/bazelbuild/rules_go/archive/%s.zip" % COMMIT,
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains()
