

cc_binary(
  name = "main",
  srcs = ["main.cc"],
  deps = [
    "@local_python_config//:python_headers",
    "@local_python_config_1//:python_headers",
    "@local_python_config_2//:python_headers",
    "@local_python_config_3//:python_headers",
    "@local_python_config_4//:python_headers",
    "@local_python_config_5//:python_headers",
    "@local_python_config_6//:python_headers",
    "@local_python_config_7//:python_headers",
    "@local_python_config_8//:python_headers",
    "@local_python_config_9//:python_headers",
    "@local_python_config_10//:python_headers",
    "@local_python_config_11//:python_headers",
    "@local_python_config_12//:python_headers",
    "@local_python_config_13//:python_headers",
    "@local_python_config_14//:python_headers",
    "@local_python_config_15//:python_headers",
    "@local_python_config_16//:python_headers",
    "@local_python_config_17//:python_headers",
    "@local_python_config_18//:python_headers",
    "@local_python_config_19//:python_headers",
    "@local_python_config_20//:python_headers",
    ],
)
