load("//:python_configure.bzl", "python_configure")

python_configure(name = "local_python_config")

python_configure(name = "local_python_config_1")
python_configure(name = "local_python_config_2")
python_configure(name = "local_python_config_3")
python_configure(name = "local_python_config_4")
python_configure(name = "local_python_config_5")
python_configure(name = "local_python_config_6")
python_configure(name = "local_python_config_7")
python_configure(name = "local_python_config_8")
python_configure(name = "local_python_config_9")
python_configure(name = "local_python_config_10")
python_configure(name = "local_python_config_11")
python_configure(name = "local_python_config_12")
python_configure(name = "local_python_config_13")
python_configure(name = "local_python_config_14")
python_configure(name = "local_python_config_15")
python_configure(name = "local_python_config_16")
python_configure(name = "local_python_config_17")
python_configure(name = "local_python_config_18")
python_configure(name = "local_python_config_19")
python_configure(name = "local_python_config_20")

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
