load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    sha256 = "0a8003b044294d7840ac7d9d73eef05d6ceb682d7516781a4ec62eeb34702578",
    strip_prefix = "rules_python-0.24.0",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.24.0/rules_python-0.24.0.tar.gz",
)

load("@rules_python//python:repositories.bzl", "py_repositories")

py_repositories()

load("@rules_python//python:repositories.bzl", "python_register_toolchains")

python_register_toolchains(
    name = "python_3_8",
    python_version = "3.8",
)

load("@python_3_8//:defs.bzl", "interpreter")

load("@rules_python//python:pip.bzl", "pip_parse")
pip_parse(
   name = "pip",
   requirements_lock = "//:requirements.txt",
   python_interpreter_target = interpreter,
)
load("@pip//:requirements.bzl", "install_deps")
install_deps()
